version: '3'
services:
  shynet:
    build:
      context: .
      target: production
    expose:
      - 8080
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis
  #     - CELERY_TASK_ALWAYS_EAGER=False
  webserver:
    container_name: shynet_webserver
    image: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf    
    ports:
      - 8080:80
    depends_on:
      - shynet
    networks:
      - internal
  # celery_worker:
  #   container_name: shynet_worker
  #   image: milesmcc/shynet:latest
  #   command: "./celeryworker.sh"
  #   depends_on:
  #     - redis
  #     - shynet
  #   networks:
  #     - internal
  #   environment:
  #     - CELERY_BROKER_URL=redis://redis
  #     - NUM_WORKERS=1
  # redis:
  #   image: "redis:alpine"
  #   networks:
  #     - internal