# Generated by Django 3.0.5 on 2020-04-10 06:58

from django.db import migrations, models

import analytics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start", models.DateTimeField(auto_now_add=True)),
                ("duration", models.FloatField(default=0.0)),
                ("heartbeats", models.IntegerField(default=0)),
                ("tracker", models.TextField()),
                ("location", models.TextField(blank=True)),
                ("referrer", models.TextField(blank=True)),
                ("loadTime", models.FloatField(null=True)),
                ("httpStatus", models.IntegerField(null=True)),
                ("metadata_raw", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=analytics.models._default_uuid,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("identifier", models.TextField(blank=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now_add=True)),
                ("user_agent", models.TextField()),
                ("browser", models.TextField()),
                ("device", models.TextField()),
                ("os", models.TextField()),
                ("ip", models.GenericIPAddressField()),
                ("asn", models.TextField(blank=True)),
                ("country", models.TextField(blank=True)),
                ("longitude", models.FloatField(null=True)),
                ("latitude", models.FloatField(null=True)),
                ("time_zone", models.TextField(blank=True)),
                ("metadata_raw", models.TextField()),
            ],
        ),
    ]
