# Generated by Django 3.0.5 on 2020-05-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_auto_20200415_1742"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="ip",
            field=models.GenericIPAddressField(db_index=True, null=True),
        ),
    ]
