# Generated by Django 3.0.5 on 2020-04-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_auto_20200411_1541"),
    ]

    operations = [
        migrations.AddField(
            model_name="hit", name="initial", field=models.BooleanField(default=True),
        ),
    ]
