# Generated by Django 3.0.5 on 2020-04-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_hit_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="hit", name="httpStatus",),
        migrations.AddField(
            model_name="session",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("PHONE", "Phone"),
                    ("TABLET", "Tablet"),
                    ("DESK", "Desktop / Laptop"),
                    ("ROBOT", "Robot"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=6,
            ),
        ),
    ]
