# Generated by Django 3.0.5 on 2020-04-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0006_auto_20200412_0003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("PHONE", "Phone"),
                    ("TABLET", "Tablet"),
                    ("DESKTOP", "Desktop"),
                    ("ROBOT", "Robot"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=7,
            ),
        ),
    ]
