# Generated by Django 3.1.7 on 2021-03-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_auto_20210328_1634"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="is_bounce",
            field=models.BooleanField(db_index=True, default=True),
        )
    ]
