# Generated by Django 3.0.5 on 2020-04-12 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0007_auto_20200412_0010"),
    ]

    operations = [
        migrations.RenameField(
            model_name="hit", old_name="loadTime", new_name="load_time",
        ),
    ]
