# Generated by Django 3.0.5 on 2020-04-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_auto_20200412_0015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hit',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start_time']},
        ),
        migrations.AlterField(
            model_name='hit',
            name='initial',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='location',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='referrer',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='identifier',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='ip',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['session', '-start_time'], name='analytics_h_session_b2667f_idx'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['session', 'location'], name='analytics_h_session_775f5a_idx'),
        ),
        migrations.AddIndex(
            model_name='hit',
            index=models.Index(fields=['session', 'referrer'], name='analytics_h_session_98b8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['service', '-start_time'], name='analytics_s_service_4b1137_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['service', 'identifier'], name='analytics_s_service_82ab21_idx'),
        ),
    ]
