# Generated by Django 3.2.12 on 2022-06-24 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20211117_0217'),
        ('analytics', '0009_auto_20210329_1100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hit',
            options={'ordering': ['-start_time'], 'verbose_name': 'Hit', 'verbose_name_plural': 'Hits'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-start_time'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.AlterField(
            model_name='hit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hit',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.session', verbose_name='Session'),
        ),
        migrations.AlterField(
            model_name='session',
            name='asn',
            field=models.TextField(blank=True, verbose_name='Asn'),
        ),
        migrations.AlterField(
            model_name='session',
            name='browser',
            field=models.TextField(verbose_name='Browser'),
        ),
        migrations.AlterField(
            model_name='session',
            name='country',
            field=models.TextField(blank=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='session',
            name='device',
            field=models.TextField(verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='session',
            name='device_type',
            field=models.CharField(choices=[('PHONE', 'Phone'), ('TABLET', 'Tablet'), ('DESKTOP', 'Desktop'), ('ROBOT', 'Robot'), ('OTHER', 'Other')], default='OTHER', max_length=7, verbose_name='Device type'),
        ),
        migrations.AlterField(
            model_name='session',
            name='identifier',
            field=models.TextField(blank=True, db_index=True, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='session',
            name='ip',
            field=models.GenericIPAddressField(db_index=True, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='session',
            name='is_bounce',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Is bounce'),
        ),
        migrations.AlterField(
            model_name='session',
            name='last_seen',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Last seen'),
        ),
        migrations.AlterField(
            model_name='session',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='session',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='session',
            name='os',
            field=models.TextField(verbose_name='OS'),
        ),
        migrations.AlterField(
            model_name='session',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='session',
            name='time_zone',
            field=models.TextField(blank=True, verbose_name='Time zone'),
        ),
        migrations.AlterField(
            model_name='session',
            name='user_agent',
            field=models.TextField(verbose_name='User agent'),
        ),
    ]
