# Generated by Django 3.0.5 on 2020-04-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="anonymize_ips",
            field=models.BooleanField(default=False),
        ),
    ]
