# Generated by Django 3.0.5 on 2020-04-11 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_service_anonymize_ips"),
    ]

    operations = [
        migrations.RemoveField(model_name="service", name="anonymize_ips",),
    ]
