# Generated by Django 3.0.5 on 2020-04-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20200415_1742"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="respect_dnt",
            field=models.BooleanField(default=True),
        ),
    ]
