# Generated by Django 3.0.6 on 2020-05-07 21:23

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_service_ignored_ips"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="hide_referrer_regex",
            field=models.TextField(
                blank=True, default="", validators=[core.models._validate_regex]
            ),
        ),
    ]
