# Generated by Django 3.0.6 on 2020-06-15 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_service_hide_referrer_regex"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="ignore_robots",
            field=models.BooleanField(default=False),
        )
    ]
